spring:
  redis:
    host: liantong.imwork.net # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 16379 # Redis服务器连接端口
    password: redis804703017
    timeout: 3000ms # 连接超时时间（毫秒）
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8201/mall-auth/rsa/publicKey'
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: localhost